# Generated by Django 2.2.3 on 2019-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AthleteName', models.CharField(max_length=200)),
                ('DoB', models.DateTimeField(verbose_name='date of birth')),
            ],
        ),
    ]
