# Generated by Django 2.2.3 on 2019-07-09 22:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentDate', models.DateField(default=datetime.date.today)),
                ('Location', models.TextField(default='Hithercroft')),
                ('Comments', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AthleteName', models.CharField(max_length=200)),
                ('DoB', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('guardian', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeightJump', models.FloatField()),
                ('BroadJump', models.FloatField()),
                ('GripStrength', models.FloatField()),
                ('Sprint', models.FloatField()),
                ('AgilityBox', models.FloatField()),
                ('FiveFromFiveTime', models.FloatField()),
                ('FiveFromFiveBalls', models.FloatField()),
                ('HitSpeed', models.FloatField()),
                ('PushSpeed', models.FloatField()),
                ('IRYY1', models.FloatField()),
                ('Comments', models.TextField()),
                ('AssessmentEvent_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.AssessmentEvent')),
                ('Athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.athlete')),
            ],
        ),
    ]
