# Generated by Django 2.2.3 on 2019-07-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='IncludeInAverages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvAgilityBox',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvBroadJump',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvFiveFromFiveBalls',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvFiveFromFiveTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvGripStrength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvHeightJump',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvHitSpeed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvIRYY1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvPushSpeed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='AvSprint',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='AgilityBox',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='BroadJump',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='FiveFromFiveBalls',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='FiveFromFiveTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='GripStrength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='HeightJump',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='HitSpeed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='IRYY1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='PushSpeed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Sprint',
            field=models.FloatField(default=0),
        ),
    ]
