# Generated by Django 2.2.3 on 2019-07-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='DoB',
            field=models.DateField(blank=True, verbose_name='date of birth'),
        ),
    ]
