# Generated by Django 2.2.3 on 2019-07-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_auto_20190706_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
