# Generated by Django 2.2.3 on 2019-07-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_auto_20190706_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='DoB',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
