# Generated by Django 2.2.3 on 2019-07-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0005_athlete_guardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeightJump', models.FloatField()),
                ('BroadJump', models.FloatField()),
                ('GripStrength', models.FloatField()),
                ('Sprint', models.FloatField()),
                ('AgilityBox', models.FloatField()),
                ('FiveFromFiveTime', models.FloatField()),
                ('FiveFromFiveBalls', models.FloatField()),
                ('HitSpeed', models.FloatField()),
                ('PushSpeed', models.FloatField()),
                ('IYRR1', models.FloatField()),
                ('Comments', models.TextField()),
                ('Athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.athlete')),
            ],
        ),
    ]
