# Generated by Django 2.2.3 on 2019-07-09 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0006_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='AssessmentDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
